---
src_vocab: '/mnt/lustre/xushuang1/cqwang/mt-data/180_mix_IWSLT15/zh_bpe_vocab.tag.39000'
dst_vocab: '/mnt/lustre/xushuang1/cqwang/mt-data/180_mix_IWSLT15/en_bpe_vocab.tag.34000'
src_vocab_size: 39000
dst_vocab_size: 34000
hidden_units: 512
scale_embedding: True
attention_dropout_rate: 0.0
residual_dropout_rate: 0.1
num_blocks: 6
num_heads: 8
train:
    devices: '0,1,2,3,4,5,6,7'
    src_path: '/mnt/lustre/xushuang1/cqwang/mt-data/180_mix_IWSLT15/zh.txt.bpe.tag'
    dst_path: '/mnt/lustre/xushuang1/cqwang/mt-data/180_mix_IWSLT15/en.txt.bpe'
    tokens_per_batch: 25000
    max_length: 125
    num_epochs: 1000
    logdir: 'model-180_mix_iwslt15_tag-bpe_bpe'
    save_freq: 1000
    summary_freq: 100
    grads_clip: 5
    optimizer: 'adam_decay'
    learning_rate: 0.0001
    learning_rate_warmup_steps: 4000
    label_smoothing: 0.1
    toleration: 10
dev:
    batch_size: 256
    src_path: '/mnt/lustre/xushuang1/cqwang/mt-data/IWSLT15/dev2010.zh.bpe.tag'
    ref_path: '/mnt/lustre/xushuang1/cqwang/mt-data/IWSLT15/dev2010.en'
    output_path: '/mnt/lustre/xushuang1/cqwang/mt-data/IWSLT15/dev2010.180_mix_iwslt15.bpe_bpe.output.tag'

test:
    batch_size: 256
    max_target_length: 200
    lp_alpha: 0.6
    beam_size: 4
    devices: '0,1,2,3,4,5,6,7'

    set1:
        src_path: '/mnt/lustre/xushuang1/cqwang/mt-data/NewTestSet/bleuTest/NIST02/NIST02.bpe.tag'
        ref_path: '/mnt/lustre/xushuang1/cqwang/mt-data/NewTestSet/bleuTest/NIST02/NIST02.ref'
        output_path: '/mnt/lustre/xushuang1/cqwang/mt-data/NewTestSet/bleuTest/NIST02/iwslt15.bpe_bpe.output.tag'
        cmd: "sh /mnt/lustre/xushuang1/cqwang/mt-data/NewTestSet/bleuTest/test.sh {ref} {output} | grep 'BLEU score =' | awk '{{print($4)}}'"
    set2:
        src_path: '/mnt/lustre/xushuang1/cqwang/mt-data/NewTestSet/bleuTest/NIST03/NIST03.bpe.tag'
        ref_path: '/mnt/lustre/xushuang1/cqwang/mt-data/NewTestSet/bleuTest/NIST03/NIST03.ref'
        output_path: '/mnt/lustre/xushuang1/cqwang/mt-data/NewTestSet/bleuTest/NIST03/iwslt15.bpe_bpe.output.tag'
        cmd: "sh /mnt/lustre/xushuang1/cqwang/mt-data/NewTestSet/bleuTest/test.sh {ref} {output} | grep 'BLEU score =' | awk '{{print($4)}}'"
    set3:
        src_path: '/mnt/lustre/xushuang1/cqwang/mt-data/NewTestSet/bleuTest/NIST04/NIST04.bpe.tag'
        ref_path: '/mnt/lustre/xushuang1/cqwang/mt-data/NewTestSet/bleuTest/NIST04/NIST04.ref'
        output_path: '/mnt/lustre/xushuang1/cqwang/mt-data/NewTestSet/bleuTest/NIST04/iwslt15.bpe_bpe.output.tag'
        cmd: "sh /mnt/lustre/xushuang1/cqwang/mt-data/NewTestSet/bleuTest/test.sh {ref} {output} | grep 'BLEU score =' | awk '{{print($4)}}'"
    set4:
        src_path: '/mnt/lustre/xushuang1/cqwang/mt-data/NewTestSet/bleuTest/NIST05/NIST05.bpe.tag'
        ref_path: '/mnt/lustre/xushuang1/cqwang/mt-data/NewTestSet/bleuTest/NIST05/NIST05.ref'
        output_path: '/mnt/lustre/xushuang1/cqwang/mt-data/NewTestSet/bleuTest/NIST05/iwslt15.bpe_bpe.output.tag'
        cmd: "sh /mnt/lustre/xushuang1/cqwang/mt-data/NewTestSet/bleuTest/test.sh {ref} {output} | grep 'BLEU score =' | awk '{{print($4)}}'"
    set5:
        src_path: '/mnt/lustre/xushuang1/cqwang/mt-data/IWSLT15/dev2010.zh.bpe.tag'
        ref_path: '/mnt/lustre/xushuang1/cqwang/mt-data/IWSLT15/dev2010.en'
        output_path: '/mnt/lustre/xushuang1/cqwang/mt-data/IWSLT15/dev2010.iwslt15.bpe_bpe.output.tag'
    set6:
        src_path: '/mnt/lustre/xushuang1/cqwang/mt-data/IWSLT15/test2010.zh.bpe.tag'
        ref_path: '/mnt/lustre/xushuang1/cqwang/mt-data/IWSLT15/test2010.en'
        output_path: '/mnt/lustre/xushuang1/cqwang/mt-data/IWSLT15/test2010.iwslt15.bpe_bpe.output.tag'
    set7:
        src_path: '/mnt/lustre/xushuang1/cqwang/mt-data/IWSLT15/test2011.zh.bpe.tag'
        ref_path: '/mnt/lustre/xushuang1/cqwang/mt-data/IWSLT15/test2011.en'
        output_path: '/mnt/lustre/xushuang1/cqwang/mt-data/IWSLT15/test2011.iwslt15.bpe_bpe.output.tag'
    set8:
        src_path: '/mnt/lustre/xushuang1/cqwang/mt-data/IWSLT15/test2012.zh.bpe.tag'
        ref_path: '/mnt/lustre/xushuang1/cqwang/mt-data/IWSLT15/test2012.en'
        output_path: '/mnt/lustre/xushuang1/cqwang/mt-data/IWSLT15/test2012.iwslt15.bpe_bpe.output.tag'
    set9:
        src_path: '/mnt/lustre/xushuang1/cqwang/mt-data/IWSLT15/test2013.zh.bpe.tag'
        ref_path: '/mnt/lustre/xushuang1/cqwang/mt-data/IWSLT15/test2013.en'
        output_path: '/mnt/lustre/xushuang1/cqwang/mt-data/IWSLT15/test2013.iwslt15.bpe_bpe.output.tag'
