---
src_vocab: '/data2/cqwang/ende/vocab.bpe.32000'
dst_vocab: '/data2/cqwang/ende/vocab.bpe.32000'
src_vocab_size: 32000
dst_vocab_size: 32000
hidden_units: 512
attention_dropout_rate: 0.0
residual_dropout_rate: 0.1
num_blocks: 6
num_heads: 8
binding_embedding: False
train:
    devices: '0,1,2,3,4,5,6,7'
    src_path: '/data2/cqwang/ende/train.tok.clean.bpe.32000.en'
    dst_path: '/data2/cqwang/ende/train.tok.clean.bpe.32000.de'
    batch_size: 256
    tokens_per_batch: 3500
    max_length: 256
    num_epochs: 500
    logdir: 'model1'
    save_freq: 1000
    grads_clip: 5
    optimizer: 'normal_adam'
    learning_rate: 0.0001
    learning_rate_warmup_steps: 4000
    label_smoothing: 0.1
test:
    src_path: '/data2/cqwang/ende/newstest2014.tok.bpe.32000.en'
    dst_path: '/data2/cqwang/ende/newstest2014.tok.de'
    output_path: '/data2/cqwang/ende/newstest2014.de.output'
    batch_size: 16
    beam_size: 1
    devices: '0'
