---
src_vocab: '/data/cqwang/mt-chen/src_vocab.40000'
dst_vocab: '/data/cqwang/mt-chen/dst_vocab.40000'
src_vocab_size: 40000
dst_vocab_size: 40000
hidden_units: 512
scale_embedding: True
attention_dropout_rate: 0.0
residual_dropout_rate: 0.1
num_blocks: 6
num_heads: 8
train:
    devices: '0,1,2,3'
    src_path: '/data/cqwang/mt-chen/chn.txt'
    dst_path: '/data/cqwang/mt-chen/eng.txt'
    tokens_per_batch: 25000
    max_length: 100
    num_epochs: 500
    logdir: 'model-ch-en-4'
    save_freq: 1000
    summary_freq: 100
    grads_clip: 5
    optimizer: 'adam_decay'
    learning_rate: 0.0001
    learning_rate_warmup_steps: 4000
    label_smoothing: 0.1
test:
    src_path: '/data/cqwang/ende/newstest2014.tok.bpe.32000.en'
    dst_path: '/data/cqwang/ende/newstest2014.tok.de'
    output_path: '/data/cqwang/ende/newstest2014.de.output'
    batch_size: 256
    max_target_length: 200
    beam_size: 4
    devices: '0,1,2,3'
