---
src_vocab: '/mnt/lustre/xushuang1/cqwang/mt-data/2400/chn_vocab.40000'
dst_vocab: '/mnt/lustre/xushuang1/cqwang/mt-data/2400/eng_vocab.40000'
src_vocab_size: 40000
dst_vocab_size: 40000
hidden_units: 512
scale_embedding: True
attention_dropout_rate: 0.0
residual_dropout_rate: 0.1
num_blocks: 6
num_heads: 8
train:
    devices: '0,1,2,3,4,5,6,7'
    src_path: '/mnt/lustre/xushuang1/cqwang/mt-data/2400/chn.txt'
    dst_path: '/mnt/lustre/xushuang1/cqwang/mt-data/2400/eng.txt'
    tokens_per_batch: 25000
    max_length: 125
    num_epochs: 500
    logdir: 'model-2400-base'
    save_freq: 1000
    summary_freq: 100
    grads_clip: 5
    optimizer: 'adam_decay'
    learning_rate: 0.0001
    learning_rate_warmup_steps: 4000
    label_smoothing: 0.1
test:
    src_path: '/mnt/lustre/xushuang1/cqwang/mt-data/NewTestSet/nist02/02.cws.bpe.end'
    ori_dst_path: 'nist02.token.ref'
    output_path: '/mnt/lustre/xushuang1/cqwang/mt-data/NewTestSet/nist02/nmt.output'
    eval_script: '/mnt/lustre/xushuang1/cqwang/mt-data/NewTestSet/nist02/postProcessAndTest.sh'

#    src_path: '/mnt/lustre/xushuang1/cqwang/mt-data/NewTestSet/IWSLT07/IWSLT07.cws.bpe.end'
#    output_path: '/mnt/lustre/xushuang1/cqwang/mt-data/NewTestSet/IWSLT07/nmt.output'

#    src_path: '/mnt/lustre/xushuang1/cqwang/mt-data/NewTestSet/nist1109/nist1109.cws.bpe.end'
#    output_path: '/mnt/lustre/xushuang1/cqwang/mt-data/NewTestSet/nist1109/nmt.output'

    batch_size: 1
    max_target_length: 200
    lp_alpha: 0.6
    beam_size: 4
    caching_decoder_outputs: False
    devices: ''
