---
model: Transformer
src_vocab: '../../parallel/news180w/zh.vocab'
dst_vocab: '../../parallel/news180w/en.vocab'
src_vocab_size: 9031
dst_vocab_size: 34218
hidden_units: 512
scale_embedding: True
tie_embedding_and_softmax: True
attention_dropout_rate: 0.0
residual_dropout_rate: 0.1
num_blocks: 6
num_heads: 8
ff_activation: 'relu'
model_dir: 'model-news'
train:
  num_gpus: 8
  src_path: '../../parallel/news180w/zh.char.txt'
  dst_path: '../../parallel/news180w/en.bpe.txt'
  tokens_per_batch: 30000
  max_length: 125
  num_epochs: 100
  num_steps: 100000
  save_freq: 1000
  show_freq: 1
  summary_freq: 100
  grads_clip: 0
  optimizer: 'adam_decay'
  learning_rate: 1
  warmup_steps: 4000
  label_smoothing: 0.1
  toleration:
  eval_on_dev: True
dev:
  batch_size: 256
  src_path: '../../parallel/test/nist02.char.txt'
  ref_path: '../../parallel/test/nist02.ref'
  output_path: 'model-news/nist02.output'

test:
  batch_size: 256
  max_target_length: 200
  lp_alpha: 0.6
  beam_size: 4
  num_gpus: 8

  set_nist02:
    src_path: '../../parallel/test/nist02.char.txt'
    ref_path: '../../parallel/test/nist02.ref'
    output_path: 'model-news/nist02.output'
  set_nist03:
    src_path: '../../parallel/test/nist03.char.txt'
    ref_path: '../../parallel/test/nist03.ref'
    output_path: 'model-news/nist03.output'
  set_nist04:
    src_path: '../../parallel/test/nist04.char.txt'
    ref_path: '../../parallel/test/nist04.ref'
    output_path: 'model-news/nist04.output'
  set_nist05:
    src_path: '../../parallel/test/nist05.char.txt'
    ref_path: '../../parallel/test/nist05.ref'
    output_path: 'model-news/nist05.output'
#  set_iwslt10dev:
#    src_path: '../../parallel/test/iwslt10dev.char.txt'
#    ref_path: '../../parallel/test/iwslt10dev.ref'
#    output_path: 'model-news/iwslt10dev.output'
#  set_iwslt10:
#    src_path: '../../parallel/test/iwslt10.char.txt'
#    ref_path: '../../parallel/test/iwslt10.ref'
#    output_path: 'model-news/iwslt10.output'
#  set_iwslt11:
#    src_path: '../../parallel/test/iwslt11.char.txt'
#    ref_path: '../../parallel/test/iwslt11.ref'
#    output_path: 'model-news/iwslt11.output'
#  set_iwslt12:
#    src_path: '../../parallel/test/iwslt12.char.txt'
#    ref_path: '../../parallel/test/iwslt12.ref'
#    output_path: 'model-news/iwslt12.output'
#  set_iwslt13:
#    src_path: '../../parallel/test/iwslt13.char.txt'
#    ref_path: '../../parallel/test/iwslt13.ref'
#    output_path: 'model-news/iwslt13.output'
